// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlswdavpjozdwhzwerub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsc3dkYXZwam96ZHdoendlcnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODYwMjIsImV4cCI6MjA2NTk2MjAyMn0.5zbSwxJ7qzd-osSYXpt6681hLCCoaba1aqJChIyUauA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);